version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_dataset:
    run: >
      databuilder:v0.34.1
        generate_dataset
        --dataset-definition analysis/dataset_definition.py
        --dataset output/dataset.csv
        --dummy-data-file dummy_output/dataset.csv
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv

  count_by_age:
    run: >
      python:latest
        python analysis/count_by_age.py
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        count: output/count_by_age.csv
