version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_dataset:
    run: >
      databuilder:v0.46.1
        generate-dataset
        --output output/dataset.csv
        --dummy-data-file dummy_output/dataset.csv
        analysis/dataset_definition.py
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv

  count_by_year:
    run: >
      python:latest
        python analysis/count_by_year.py
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        count: output/count_by_year.csv
